version: '3'

services:
  spring:
    image: gramo-build
    build: .
    container_name: gramo-backend
    ports:
    - "8001:8001"
    volumes:
    - /home/hong/projects/GRAMO-Backend-SpringBoot/log:/logs/*.log
  redis:
    image: redis
    container_name: redis-gramo-server
    ports:
      - "6381:6379"
    networks:
      - redis-network

networks:
  redis-network: