version: '3'

services:
  spring:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "8001:8001"
    volumes:
    - /home/hong/projects/GRAMO-Backend-SpringBoot/log:/logs/*.log