auth:
  jwt:
    exp:
      access: ${ACCESS_TOKEN_EXP}
      refresh: ${REFRESH_TOKEN_EXP}
    secret: ${GRAMO_SECRET}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${GRAMO_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  redis:
    port: 6379
    host: redis-gramo-server
  jpa:
    generate-ddl: true      # 자동으로 DDL을 생성 할 것인가
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
server:
  port: 8082
