auth:
  jwt:
    exp:
      access: 6000
      refresh: 600000
    secret: suuuuper
    header: Authorization
    prefix: Bearer
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gramo_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qlalfqjsgh1!
  jpa:
    generate-ddl: true      # 자동으로 DDL을 생성 할 것인가
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
